export enum ActionType {
  GET_TOURNAMENTS_START = 'GET_TOURNAMENTS_START',
  GET_TOURNAMENTS_SUCCESS = 'GET_TOURNAMENTS_SUCCESS',
  GET_TOURNAMENTS_ERROR = 'GET_TOURNAMENTS_ERROR',
  ADD_TOURNAMENT = 'ADD_TOURNAMENT',
  DELETE_TOURNAMENT = 'DELETE_TOURNAMENT',
  UPDATE_TOURNAMENT = 'UPDATE_TOURNAMENT'
}
